### PR TITLE
Exploration: Browserify

### PR DESCRIPTION
**Pull request by jamesramsay**
Exploratory PR relating to #209 

```
npm run compile
npm run browserify
open index.html
```

/cc @jmatsushita

### CODE REVIEW

**Comment by jmatsushita** [comment]
Hi James, I was looking at this today and the browserification works. I was studying your code to see what the moving parts where. Hope you don't mind if I ask a few questions. 

I was looking at the grammar and the semantics in the code, and I think that if we try to find the right abstraction for resolving/inflating other type of links or links that reside somewhere else than in the nodejs filesystem or behind an http endpoint, then maybe ```localLink``` is a bit confusing or not general enough and reverting to the URI standard components naming might be a good thing?

```
                    hierarchical part
        ┌───────────────────┴─────────────────────┐
                    authority               path
        ┌───────────────┴───────────────┐┌───┴────┐
  abc://username:password@example.com:123/path/data?key=value#fragid1
  └┬┘   └───────┬───────┘ └────┬────┘ └┬┘           └───┬───┘ └──┬──┘
scheme  user information     host     port            query   fragment

```

I was thinking about my particular use case which is to:
 1. Have documents stored in a git repo (github specifically for now) transclude other documents in the same or other git repos.
 2. Render or inflate these transcluded documents in a webapp (Prose)

It seems that using a relative link (to the same repo) on Github (for instance) would mean that the graceful degradation of your syntax would point to the right file. Which is of course great to try to preserve. Linking cross repo, would mean that the URL should probably point to the HTTP endpoint for Github (or Gitlab...).

So in my case when I'm tackling 2. (and given that Prose is a Backbone app which loads Github content into its Model) then I guess the approach would be:
 a. Parse the document in the backbone model
 b. If it's a relative link then resolve the link by querying the model.
 c. If it's an absolute link then see if we have the data in the model, and if not load it.

I think this means for the "Local link handler API" some smart combination of what is handled and the resolution stage vs the inflation stage. I haven't wrapped my head around how that would work though. Maybe by allowing to pass a Resolution function and a Inflation function as part of an `options` object to the Transclude* functions?

This might all be super clear to you already :) But I thought I'd share what I've been mulling over while investigating the issue.

**Comment by jmatsushita** [comment]
I think I posted this diagram because it's pretty and it doesn't really mean much with my point :) The more important part of referring to the standard is to refer to Relative vs Absolute instead of Local vs HTTP. And maybe hint at the fact that there might be a bit more to it such as an implicit scheme. I.e. in your current implementation RelativeLinks have a file:/// implicit scheme.

**Comment by jamesramsay** [comment]
I agree the internals around link handling is quite specific and naming isn't very accurate. Refactoring this code is definitely on my radar before working out an API for link inflation. Early on I split link handling into `resolve` and `inflate` steps which in hind sight wasn't really the best move.

I'm currently working on some changes to consolidate related path handling and inflation logic to a single point. This would isolate considerations for handling relative and absolute links.

**Comment by jamesramsay** [comment]
@jmatsushita I've been working towards some of this in #235. I haven't had as much time as I'd hoped to work on this the last few weeks.

**Comment by jamesramsay** [comment]
Closed in favour of #265.

**Pull request closed without merging**
