### PR TITLE
Support a custom logger for errors

### PR DESCRIPTION
**Pull request by dgileadi**
The current code offers the ability to provide a custom logger for debug messages, but offers no customization for error logging (which can happen due to file-not-found errors or HTTP errors). This pull request adds support for making the logger argument be an object with `debug` and `error` functions. If no logger argument is provided or if the logger argument is a function then the current behavior is used.

### CODE REVIEW

**Comment by jamesramsay** [comment]
Great improvement :+1: Looks like something weird is going on with coverage though.

**Comment by dgileadi** [comment]
Is there anything you'd like me to change on this? I'm not sure what the story is with the coverage...

**Comment by jamesramsay** [comment]
@dgileadi could you rebase the commit? I think that will fix the coverage calculation and then I'll be happy to merge. Thanks again! :rocket:

**Comment by jamesramsay** [comment]
Could you rebase rather than merge? It makes for a cleaner Git history since the merge commit isn't needed.

Try: `git fetch upstream && git rebase -i upstream/master` (I'm assuming that you have a remote configured `upstream).

**Comment by dgileadi** [comment]
Yeah, I'll go ahead. I had a knee-jerk reaction of "never rebase after pushing" but I think rewriting history is fine in this case.

**Comment by jamesramsay** [comment]
Brilliant! Thanks @dgileadi :shipit:

**Pull request merged**
